"""add admin

Revision ID: 2545de037242
Revises: 67dda2dc3d39
Create Date: 2025-05-26 21:14:26.052058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2545de037242'
down_revision = '67dda2dc3d39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategori',
    sa.Column('kategori_id', sa.Integer(), nullable=False),
    sa.Column('nama_kategori', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('kategori_id', name=op.f('pk_kategori'))
    )
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('role_id', name=op.f('pk_roles'))
    )
    op.create_table('menu',
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('kategori_id', sa.Integer(), nullable=False),
    sa.Column('nama_menu', sa.String(length=255), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('harga', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategori.kategori_id'], name=op.f('fk_menu_kategori_id_kategori')),
    sa.PrimaryKeyConstraint('menu_id', name=op.f('pk_menu'))
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total_harga', sa.Integer(), nullable=False),
    sa.Column('pembayaran', sa.String(length=50), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_orders_user_id_users')),
    sa.PrimaryKeyConstraint('order_id', name=op.f('pk_orders'))
    )
    op.create_table('keranjang',
    sa.Column('keranjang_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.menu_id'], name=op.f('fk_keranjang_menu_id_menu')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name=op.f('fk_keranjang_order_id_orders')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_keranjang_user_id_users')),
    sa.PrimaryKeyConstraint('keranjang_id', name=op.f('pk_keranjang'))
    )
    op.create_table('orderdetails',
    sa.Column('detail_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.menu_id'], name=op.f('fk_orderdetails_menu_id_menu')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], name=op.f('fk_orderdetails_order_id_orders')),
    sa.PrimaryKeyConstraint('detail_id', name=op.f('pk_orderdetails'))
    )
    op.drop_table('menu_makanan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_makanan',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('menu', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('kategori', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('harga', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stok', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_makanan'))
    )
    op.drop_table('orderdetails')
    op.drop_table('keranjang')
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('menu')
    op.drop_table('roles')
    op.drop_table('kategori')
    # ### end Alembic commands ###
